SELECT TOP 10 * FROM View_GRN WHERE BUID=1 AND GRNType=6 AND GRNStatus=2 AND ISNULL(ReceivedBy,0)!=0 AND GRNID NOT IN (SELECT HH.PKValue FROM VoucherMapping AS HH WHERE HH.TableName='GRN' AND HH.PKColumnName='GRNID' AND HH.VoucherSetup=25) ORDER BY GRNID ASC
SELECT HH.BUID FROM GRN AS HH WHERE HH.GRNID=18
SELECT HH.GRNDate FROM GRN AS HH WHERE HH.GRNID=18
SELECT 'Goods received for GRN No :'+HH.GRNNo+' with Import PI No : '+ HH.RefObjectNo FROM View_GRN AS HH WHERE HH.GRNID=18
SELECT * FROM View_GRN AS HH WHERE HH.GRNID=18
SELECT HH.CurrencyID FROM GRN AS HH WHERE HH.GRNID=18
SELECT HH.ConversionRate FROM GRN AS HH WHERE HH.GRNID=18
SELECT HH.Amount FROM View_GRN AS HH WHERE HH.GRNID=18
SELECT SUM(HH.Amount) FROM View_GRNDetail AS HH WHERE HH.GRNID=18
SELECT 'Goods received for GRN No :'+HH.GRNNo+' with Import PI No : '+ HH.RefObjectNo FROM View_GRN AS HH WHERE HH.GRNID=18
SELECT * FROM View_GRNDetail WHERE GRNID=18
SELECT HH.StoreID FROM GRN AS HH WHERE HH.GRNID=18
SELECT HH.ProductID FROM GRNDetail AS HH WHERE HH.GRNDetailID=18
SELECT HH.ReceivedQty FROM GRNDetail AS HH WHERE HH.GRNDetailID=18
SELECT HH.MUnitID FROM GRNDetail AS HH WHERE HH.GRNDetailID=18
SELECT HH.UnitPrice FROM GRNDetail AS HH WHERE HH.GRNDetailID=18
SELECT HH.ReceivedQty FROM GRNDetail AS HH WHERE HH.GRNDetailID=18
SELECT HH.ReceivedDateTime FROM GRN AS HH WHERE HH.GRNID=18
SELECT 'M.I.T A/C' AS FixedAccountHead FROM GRN WHERE GRNID=18
SELECT VOrderID FROM View_VOrder AS HH WHERE HH.VOrderRefType=3 AND HH.VOrderRefID=18
SELECT HH.RefObjectID FROM GRN AS HH WHERE HH.GRNID=18
SELECT HH.RefObjectNo FROM View_GRN AS HH WHERE HH.GRNID=18
SELECT HH.Amount FROM View_GRN AS HH WHERE HH.GRNID=18
SELECT HH.ReceivedDateTime FROM View_GRN AS HH WHERE HH.GRNID=18
SELECT 'GRN No :'+ HH.GRNNo FROM GRN AS HH WHERE HH.GRNID=18
SELECT BaseCurrencyID FROM Company WHERE CompanyID=1
SELECT 1 AS CRate FROM GRN AS HH WHERE HH.GRNID=18
SELECT * FROM View_GRNDetail AS HH WHERE HH.GRNID=18

SELECT * FROM GRN WHERE GRNID=23
SELECT * FROM GRN WHERE StoreID NOT IN (SELECT WorkingUnitID FROM WorkingUnit)

SELECT MM.ACCostCenterID FROM ACCostCenter AS MM WHERE MM.ReferenceType=1 AND MM.ReferenceObjectID = 1
SELECT ContractorID, VendorName FROM View_GRN WHERE GRNID=18

SELECT * FROM ACCostCenter WHERE ParentID=1

